version: "3.3"
services:
  sqlfssprout:
    image: mysql/mysql-server:5.6
    container_name: sprout-backend
    restart: unless-stopped
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=sprout
      - MYSQL_USER=root
      - MYSQL_PASSWORD=moshi
      - MYSQL_ROOT_PASSWORD=moshi
      - MYSQL_ROOT_HOST=%
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"

  redisfssprout:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    command: "redis-server --requirepass moshi --port 6379"
