version: "3.3"
services:
  sqlfssprout:
    image: mysql/mysql-server:5.6
    container_name: sprout-backend
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:${MYSQL_TUNNEL}"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD={MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"

  redisfssprout:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_REPLICATION_MODE=master
    command: "redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}"
